version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://illiakarol:1234@db:5432/protettask_db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: illiakarol
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: protettask_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
